const definitions = {
  DESKTOP_MIN_WIDTH: 1170,
  TIMELINE_EVENT_WIDTH: 200,
  TIMELINE_EVENT_SIZE_MOBILE: 90,
  MAIN_SECTION_MAX_WIDTH: 900,
  YEAR_MARK_SIZE: 100,
  SMALL_DEVICES_MIN_WIDTH: 750
};

export default definitions;
